default:
  from:
    adapter: mysql2
    host: localhost
    port: 3306
    username: root
    password: root
  to:
    adapter: mysql2
    host: localhost
    port: 3306
    username: root
    password: root

staging:
  <<: &default

test:
  <<: &default

production:
  <<: &default


